---
title: "hw5"
author: "Yan Li"
date: "2024-11-13"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(ggplot2)
library(readxl)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


# Problem 1
## Birthday Function
```{r}
bday_dupes = function(n) {

  bdays = sample(1:365, size = n, replace = TRUE)
  
  has_dupe = any(duplicated(bdays))
  
  return(has_dupe)
}

```
## Run function for different group size
```{r}
set.seed(123)
results = map_df(2:50, function(n) {
  dupes = map_lgl(1:10000, ~ bday_dupes(n))
  prob = mean(dupes)
  tibble(group_size = n, prob = prob)
})
```
## Plot
```{r}
ggplot(results, aes(x = group_size, y = prob)) +
  geom_line() +
  labs(
    title = "Problem 1:Birthday Function",
    x = "Group Size",
    y = "Probability of Shared Birthday"
  )
```
- The probability of shared birthday increases as the group size increases, and the growth in probability is nonlinear.




